version: 0.2

phases:
  inatall:
    commands:
      - "apt install unzip -y"
      - "wget https://https://releases.hashicorp.com/terraform/1.2.3/terraform_1.2.3_linux_amd64.zip"
      - "unzip terraform_1.2.3_linux_amd64.zip"
      - "mv terraform /usr/local/bin"
    pre_build:
      commands:
        - terraform init
    build:
      commands:
        - terraform $TF_COMMAND -auto-approve
    
    post_build:
      commands:
        -echo terraform $TF_COMMAND completed on 'date'

